services:
  ponti-db:
    image: postgres:16.3
    ports:
      - "${DB_PORT}:${DB_PORT}"
    env_file:
      - .env
      - .env.${DEPLOY_PLATFORM}.${DEPLOY_ENV}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ponti-db_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ponti_api_db -p ${DB_PORT}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  app-network:
    driver: bridge

volumes:
  ponti-db_data: