services:
  ponti-db:
    image: postgres:16.3
    ports:
      - "${DB_PORT}:${DB_PORT}"
    env_file:
      - .env
      - .env.${DEPLOY_PLATFORM}.${DEPLOY_ENV}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ponti-db_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ponti_api_db -p ${DB_PORT}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  migrate:
    image: migrate/migrate:v4.17.1
    depends_on:
      ponti-db:
        condition: service_healthy
    env_file:
      - .env
      - .env.${DEPLOY_PLATFORM}.${DEPLOY_ENV}
    volumes:
      - ./migrations:/migrations
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_SSL_MODE=${DB_SSL_MODE}
    command: [
      "-path", "/migrations",
      "-database", "postgres://${DB_USER}:${DB_PASSWORD}@ponti-db:${DB_PORT}/ponti_api_db?sslmode=${DB_SSL_MODE}",
      "up"
    ]
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:8.12
    ports:
      - "${PGADMIN_PORT}:${PGADMIN_TARGET_PORT}"
    env_file:
      - .env
      - .env.${DEPLOY_PLATFORM}.${DEPLOY_ENV}
    environment:
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      GUNICORN_ACCESS_LOGFILE: "/dev/null"
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 30
    logging:
      driver: "json-file"
    depends_on:
      - ponti-db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  ponti-db_data:
  pgadmin_data: