// Code generated by MockGen. DO NOT EDIT.
// Source: internal/supply_movement/usecases.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/alphacodinggroup/ponti-backend/projects/ponti-api/internal/provider/usecase/domain"
	domain0 "github.com/alphacodinggroup/ponti-backend/projects/ponti-api/internal/supply_movement/usecases/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockRepositoryPort is a mock of RepositoryPort interface.
type MockRepositoryPort struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryPortMockRecorder
}

// MockRepositoryPortMockRecorder is the mock recorder for MockRepositoryPort.
type MockRepositoryPortMockRecorder struct {
	mock *MockRepositoryPort
}

// NewMockRepositoryPort creates a new mock instance.
func NewMockRepositoryPort(ctrl *gomock.Controller) *MockRepositoryPort {
	mock := &MockRepositoryPort{ctrl: ctrl}
	mock.recorder = &MockRepositoryPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryPort) EXPECT() *MockRepositoryPortMockRecorder {
	return m.recorder
}

// CreateProvider mocks base method.
func (m *MockRepositoryPort) CreateProvider(arg0 context.Context, arg1 *domain.Provider) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProvider", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProvider indicates an expected call of CreateProvider.
func (mr *MockRepositoryPortMockRecorder) CreateProvider(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProvider", reflect.TypeOf((*MockRepositoryPort)(nil).CreateProvider), arg0, arg1)
}

// CreateSupplyMovement mocks base method.
func (m *MockRepositoryPort) CreateSupplyMovement(arg0 context.Context, arg1 *domain0.SupplyMovement) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSupplyMovement", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSupplyMovement indicates an expected call of CreateSupplyMovement.
func (mr *MockRepositoryPortMockRecorder) CreateSupplyMovement(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSupplyMovement", reflect.TypeOf((*MockRepositoryPort)(nil).CreateSupplyMovement), arg0, arg1)
}

// DeleteSupplyMovement mocks base method.
func (m *MockRepositoryPort) DeleteSupplyMovement(arg0 context.Context, arg1, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSupplyMovement", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSupplyMovement indicates an expected call of DeleteSupplyMovement.
func (mr *MockRepositoryPortMockRecorder) DeleteSupplyMovement(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSupplyMovement", reflect.TypeOf((*MockRepositoryPort)(nil).DeleteSupplyMovement), arg0, arg1, arg2)
}

// GetEntriesSupplyMovementsByProjectID mocks base method.
func (m *MockRepositoryPort) GetEntriesSupplyMovementsByProjectID(arg0 context.Context, arg1 int64) ([]*domain0.SupplyMovement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntriesSupplyMovementsByProjectID", arg0, arg1)
	ret0, _ := ret[0].([]*domain0.SupplyMovement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEntriesSupplyMovementsByProjectID indicates an expected call of GetEntriesSupplyMovementsByProjectID.
func (mr *MockRepositoryPortMockRecorder) GetEntriesSupplyMovementsByProjectID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntriesSupplyMovementsByProjectID", reflect.TypeOf((*MockRepositoryPort)(nil).GetEntriesSupplyMovementsByProjectID), arg0, arg1)
}

// GetProviders mocks base method.
func (m *MockRepositoryPort) GetProviders(arg0 context.Context) ([]domain.Provider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProviders", arg0)
	ret0, _ := ret[0].([]domain.Provider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProviders indicates an expected call of GetProviders.
func (mr *MockRepositoryPortMockRecorder) GetProviders(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProviders", reflect.TypeOf((*MockRepositoryPort)(nil).GetProviders), arg0)
}

// GetSupplyMovementByID mocks base method.
func (m *MockRepositoryPort) GetSupplyMovementByID(arg0 context.Context, arg1 int64) (*domain0.SupplyMovement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSupplyMovementByID", arg0, arg1)
	ret0, _ := ret[0].(*domain0.SupplyMovement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSupplyMovementByID indicates an expected call of GetSupplyMovementByID.
func (mr *MockRepositoryPortMockRecorder) GetSupplyMovementByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupplyMovementByID", reflect.TypeOf((*MockRepositoryPort)(nil).GetSupplyMovementByID), arg0, arg1)
}

// UpdateSupplyMovement mocks base method.
func (m *MockRepositoryPort) UpdateSupplyMovement(arg0 context.Context, arg1 *domain0.SupplyMovement) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSupplyMovement", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSupplyMovement indicates an expected call of UpdateSupplyMovement.
func (mr *MockRepositoryPortMockRecorder) UpdateSupplyMovement(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSupplyMovement", reflect.TypeOf((*MockRepositoryPort)(nil).UpdateSupplyMovement), arg0, arg1)
}

// MockExporterAdapterPort is a mock of ExporterAdapterPort interface.
type MockExporterAdapterPort struct {
	ctrl     *gomock.Controller
	recorder *MockExporterAdapterPortMockRecorder
}

// MockExporterAdapterPortMockRecorder is the mock recorder for MockExporterAdapterPort.
type MockExporterAdapterPortMockRecorder struct {
	mock *MockExporterAdapterPort
}

// NewMockExporterAdapterPort creates a new mock instance.
func NewMockExporterAdapterPort(ctrl *gomock.Controller) *MockExporterAdapterPort {
	mock := &MockExporterAdapterPort{ctrl: ctrl}
	mock.recorder = &MockExporterAdapterPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExporterAdapterPort) EXPECT() *MockExporterAdapterPortMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockExporterAdapterPort) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockExporterAdapterPortMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockExporterAdapterPort)(nil).Close))
}

// Export mocks base method.
func (m *MockExporterAdapterPort) Export(ctx context.Context, items []*domain0.SupplyMovement) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Export", ctx, items)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Export indicates an expected call of Export.
func (mr *MockExporterAdapterPortMockRecorder) Export(ctx, items interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Export", reflect.TypeOf((*MockExporterAdapterPort)(nil).Export), ctx, items)
}
