// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/alphacodinggroup/ponti-backend/projects/ponti-api/internal/stock (interfaces: UseCasesPort)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/alphacodinggroup/ponti-backend/projects/ponti-api/internal/stock/usecases/domain"
	gomock "github.com/golang/mock/gomock"
	decimal "github.com/shopspring/decimal"
)

// MockUseCasesPort is a mock of UseCasesPort interface.
type MockUseCasesPort struct {
	ctrl     *gomock.Controller
	recorder *MockUseCasesPortMockRecorder
}

// MockUseCasesPortMockRecorder is the mock recorder for MockUseCasesPort.
type MockUseCasesPortMockRecorder struct {
	mock *MockUseCasesPort
}

// NewMockUseCasesPort creates a new mock instance.
func NewMockUseCasesPort(ctrl *gomock.Controller) *MockUseCasesPort {
	mock := &MockUseCasesPort{ctrl: ctrl}
	mock.recorder = &MockUseCasesPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUseCasesPort) EXPECT() *MockUseCasesPortMockRecorder {
	return m.recorder
}

// CreateStock mocks base method.
func (m *MockUseCasesPort) CreateStock(arg0 context.Context, arg1 *domain.Stock) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStock", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStock indicates an expected call of CreateStock.
func (mr *MockUseCasesPortMockRecorder) CreateStock(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStock", reflect.TypeOf((*MockUseCasesPort)(nil).CreateStock), arg0, arg1)
}

// ExportAllStocks mocks base method.
func (m *MockUseCasesPort) ExportAllStocks(arg0 context.Context) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportAllStocks", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExportAllStocks indicates an expected call of ExportAllStocks.
func (mr *MockUseCasesPortMockRecorder) ExportAllStocks(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportAllStocks", reflect.TypeOf((*MockUseCasesPort)(nil).ExportAllStocks), arg0)
}

// GetLastStockByProjectId mocks base method.
func (m *MockUseCasesPort) GetLastStockByProjectId(arg0 context.Context, arg1, arg2 int64) (*domain.Stock, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastStockByProjectId", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.Stock)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLastStockByProjectId indicates an expected call of GetLastStockByProjectId.
func (mr *MockUseCasesPortMockRecorder) GetLastStockByProjectId(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastStockByProjectId", reflect.TypeOf((*MockUseCasesPort)(nil).GetLastStockByProjectId), arg0, arg1, arg2)
}

// GetStockById mocks base method.
func (m *MockUseCasesPort) GetStockById(arg0 context.Context, arg1 int64) (*domain.Stock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStockById", arg0, arg1)
	ret0, _ := ret[0].(*domain.Stock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStockById indicates an expected call of GetStockById.
func (mr *MockUseCasesPortMockRecorder) GetStockById(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStockById", reflect.TypeOf((*MockUseCasesPort)(nil).GetStockById), arg0, arg1)
}

// GetStocksPeriods mocks base method.
func (m *MockUseCasesPort) GetStocksPeriods(arg0 context.Context, arg1 int64) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStocksPeriods", arg0, arg1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStocksPeriods indicates an expected call of GetStocksPeriods.
func (mr *MockUseCasesPortMockRecorder) GetStocksPeriods(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStocksPeriods", reflect.TypeOf((*MockUseCasesPort)(nil).GetStocksPeriods), arg0, arg1)
}

// GetStocksSummary mocks base method.
func (m *MockUseCasesPort) GetStocksSummary(arg0 context.Context, arg1 int64, arg2 time.Time) ([]*domain.Stock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStocksSummary", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*domain.Stock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStocksSummary indicates an expected call of GetStocksSummary.
func (mr *MockUseCasesPortMockRecorder) GetStocksSummary(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStocksSummary", reflect.TypeOf((*MockUseCasesPort)(nil).GetStocksSummary), arg0, arg1, arg2)
}

// UpdateCloseDateByProject mocks base method.
func (m *MockUseCasesPort) UpdateCloseDateByProject(arg0 context.Context, arg1, arg2, arg3 int64, arg4 *domain.Stock) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCloseDateByProject", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCloseDateByProject indicates an expected call of UpdateCloseDateByProject.
func (mr *MockUseCasesPortMockRecorder) UpdateCloseDateByProject(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCloseDateByProject", reflect.TypeOf((*MockUseCasesPort)(nil).UpdateCloseDateByProject), arg0, arg1, arg2, arg3, arg4)
}

// UpdateRealStockUnits mocks base method.
func (m *MockUseCasesPort) UpdateRealStockUnits(arg0 context.Context, arg1 int64, arg2 *domain.Stock) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRealStockUnits", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRealStockUnits indicates an expected call of UpdateRealStockUnits.
func (mr *MockUseCasesPortMockRecorder) UpdateRealStockUnits(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRealStockUnits", reflect.TypeOf((*MockUseCasesPort)(nil).UpdateRealStockUnits), arg0, arg1, arg2)
}

// UpdateUnitsConsumed mocks base method.
func (m *MockUseCasesPort) UpdateUnitsConsumed(arg0 context.Context, arg1 domain.Stock, arg2 decimal.Decimal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUnitsConsumed", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUnitsConsumed indicates an expected call of UpdateUnitsConsumed.
func (mr *MockUseCasesPortMockRecorder) UpdateUnitsConsumed(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUnitsConsumed", reflect.TypeOf((*MockUseCasesPort)(nil).UpdateUnitsConsumed), arg0, arg1, arg2)
}
