DELETE FROM crops WHERE id BETWEEN 1 AND 10;
DELETE FROM lease_types WHERE name IN (
  '% INGRESO NETO', '% UTILIDAD', 'ARRIENDO FIJO', 'ARRIENDO FIJO + % INGRESO NETO'
);
DELETE FROM labor_types WHERE id BETWEEN 1 AND 4;
DELETE FROM labor_categories WHERE id BETWEEN 1 AND 13