-- ========================================
-- MIGRATION 000093: FIX labor group endpoint (UP)
-- ========================================
--
-- Purpose: Fix labor group endpoint to use LEFT JOIN with project_dollar_values
--          and fallback to dollar_average_for_month function
-- Date: 2025-01-27
-- Author: System
--
-- Note: Code in English, comments in Spanish.

-- No hay cambios en la base de datos, solo en el código Go
-- El problema está en el repository que usa INNER JOIN en lugar de LEFT JOIN
-- y no usa la función dollar_average_for_month como fallback
