// Code generated by MockGen. DO NOT EDIT.
// Source: usecases.go

// Package mock_lot is a generated GoMock package.
package mock_lot

import (
	context "context"
	reflect "reflect"

	domain "github.com/alphacodinggroup/ponti-backend/projects/ponti-api/internal/lot/usecases/domain"
	gomock "github.com/golang/mock/gomock"
	decimal "github.com/shopspring/decimal"
)

// MockRepositoryPort is a mock of RepositoryPort interface.
type MockRepositoryPort struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryPortMockRecorder
}

// MockRepositoryPortMockRecorder is the mock recorder for MockRepositoryPort.
type MockRepositoryPortMockRecorder struct {
	mock *MockRepositoryPort
}

// NewMockRepositoryPort creates a new mock instance.
func NewMockRepositoryPort(ctrl *gomock.Controller) *MockRepositoryPort {
	mock := &MockRepositoryPort{ctrl: ctrl}
	mock.recorder = &MockRepositoryPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryPort) EXPECT() *MockRepositoryPortMockRecorder {
	return m.recorder
}

// CreateLot mocks base method.
func (m *MockRepositoryPort) CreateLot(arg0 context.Context, arg1 *domain.Lot) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLot", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLot indicates an expected call of CreateLot.
func (mr *MockRepositoryPortMockRecorder) CreateLot(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLot", reflect.TypeOf((*MockRepositoryPort)(nil).CreateLot), arg0, arg1)
}

// DeleteLot mocks base method.
func (m *MockRepositoryPort) DeleteLot(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLot", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLot indicates an expected call of DeleteLot.
func (mr *MockRepositoryPortMockRecorder) DeleteLot(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLot", reflect.TypeOf((*MockRepositoryPort)(nil).DeleteLot), arg0, arg1)
}

// GetLot mocks base method.
func (m *MockRepositoryPort) GetLot(arg0 context.Context, arg1 int64) (*domain.Lot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLot", arg0, arg1)
	ret0, _ := ret[0].(*domain.Lot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLot indicates an expected call of GetLot.
func (mr *MockRepositoryPortMockRecorder) GetLot(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLot", reflect.TypeOf((*MockRepositoryPort)(nil).GetLot), arg0, arg1)
}

// GetMetrics mocks base method.
func (m *MockRepositoryPort) GetMetrics(arg0 context.Context, arg1, arg2, arg3 int64) (*domain.LotMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetrics", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*domain.LotMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetrics indicates an expected call of GetMetrics.
func (mr *MockRepositoryPortMockRecorder) GetMetrics(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetrics", reflect.TypeOf((*MockRepositoryPort)(nil).GetMetrics), arg0, arg1, arg2, arg3)
}

// ListLots mocks base method.
func (m *MockRepositoryPort) ListLots(arg0 context.Context, arg1, arg2, arg3 int64, arg4, arg5 int) ([]domain.LotTable, int, decimal.Decimal, decimal.Decimal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLots", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].([]domain.LotTable)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(decimal.Decimal)
	ret3, _ := ret[3].(decimal.Decimal)
	ret4, _ := ret[4].(error)
	return ret0, ret1, ret2, ret3, ret4
}

// ListLots indicates an expected call of ListLots.
func (mr *MockRepositoryPortMockRecorder) ListLots(arg0, arg1, arg2, arg3, arg4, arg5 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLots", reflect.TypeOf((*MockRepositoryPort)(nil).ListLots), arg0, arg1, arg2, arg3, arg4, arg5)
}

// ListLotsByField mocks base method.
func (m *MockRepositoryPort) ListLotsByField(arg0 context.Context, arg1 int64) ([]domain.Lot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLotsByField", arg0, arg1)
	ret0, _ := ret[0].([]domain.Lot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLotsByField indicates an expected call of ListLotsByField.
func (mr *MockRepositoryPortMockRecorder) ListLotsByField(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLotsByField", reflect.TypeOf((*MockRepositoryPort)(nil).ListLotsByField), arg0, arg1)
}

// ListLotsByProject mocks base method.
func (m *MockRepositoryPort) ListLotsByProject(arg0 context.Context, arg1 int64) ([]domain.Lot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLotsByProject", arg0, arg1)
	ret0, _ := ret[0].([]domain.Lot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLotsByProject indicates an expected call of ListLotsByProject.
func (mr *MockRepositoryPortMockRecorder) ListLotsByProject(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLotsByProject", reflect.TypeOf((*MockRepositoryPort)(nil).ListLotsByProject), arg0, arg1)
}

// ListLotsByProjectAndField mocks base method.
func (m *MockRepositoryPort) ListLotsByProjectAndField(arg0 context.Context, arg1, arg2 int64) ([]domain.Lot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLotsByProjectAndField", arg0, arg1, arg2)
	ret0, _ := ret[0].([]domain.Lot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLotsByProjectAndField indicates an expected call of ListLotsByProjectAndField.
func (mr *MockRepositoryPortMockRecorder) ListLotsByProjectAndField(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLotsByProjectAndField", reflect.TypeOf((*MockRepositoryPort)(nil).ListLotsByProjectAndField), arg0, arg1, arg2)
}

// ListLotsByProjectFieldAndCrop mocks base method.
func (m *MockRepositoryPort) ListLotsByProjectFieldAndCrop(arg0 context.Context, arg1, arg2, arg3 int64, arg4 string) ([]domain.Lot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLotsByProjectFieldAndCrop", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]domain.Lot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLotsByProjectFieldAndCrop indicates an expected call of ListLotsByProjectFieldAndCrop.
func (mr *MockRepositoryPortMockRecorder) ListLotsByProjectFieldAndCrop(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLotsByProjectFieldAndCrop", reflect.TypeOf((*MockRepositoryPort)(nil).ListLotsByProjectFieldAndCrop), arg0, arg1, arg2, arg3, arg4)
}

// UpdateLot mocks base method.
func (m *MockRepositoryPort) UpdateLot(arg0 context.Context, arg1 *domain.Lot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLot", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLot indicates an expected call of UpdateLot.
func (mr *MockRepositoryPortMockRecorder) UpdateLot(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLot", reflect.TypeOf((*MockRepositoryPort)(nil).UpdateLot), arg0, arg1)
}

// UpdateLotTons mocks base method.
func (m *MockRepositoryPort) UpdateLotTons(arg0 context.Context, arg1 int64, arg2 decimal.Decimal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLotTons", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLotTons indicates an expected call of UpdateLotTons.
func (mr *MockRepositoryPortMockRecorder) UpdateLotTons(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLotTons", reflect.TypeOf((*MockRepositoryPort)(nil).UpdateLotTons), arg0, arg1, arg2)
}
